apiVersion: v1
kind: Pod
metadata:
  name: configmap-1-1
spec:
  containers:
  - name: configmap-1-1
    image: busybox
    args: ['tail', '-f', '/dev/null']
    envFrom:
    - configMapRef:
        name: pet  # 참조할 ConfigMap 이름
