apiVersion: v1
kind: Pod
metadata:
  name: configmap-2-1
spec:
  containers:
  - name: configmap-2-1
    image: busybox
    args: ['tail', '-f', '/dev/null']
    volumeMounts:
    - name: configmap-volume  # volumes[].name과 맞춰주기
      mountPath: /etc/config
  volumes:
  - name: configmap-volume  # volumeMounts[].name과 맞춰주기
    configMap:
      name: pet  # 참조할 ConfigMap 이름
